# Generated by Django 5.2.16 on 2026-07-20 10:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('drivers', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('rc', 'Registration certificate'), ('insurance', 'Insurance'), ('permit', 'Permit'), ('national_permit', 'National permit'), ('fitness', 'Fitness certificate'), ('puc', 'Pollution under control'), ('road_tax', 'Road tax'), ('licence', 'Driving licence'), ('badge', 'Badge'), ('police_verification', 'Police verification'), ('medical_certificate', 'Medical certificate'), ('other', 'Other')], max_length=24)),
                ('doc_number', models.CharField(blank=True, max_length=60)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('valid_till', models.DateField(blank=True, null=True)),
                ('reminder_days_before', models.PositiveIntegerField(default=30)),
                ('file', models.FileField(blank=True, null=True, upload_to='compliance/')),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='drivers.driver')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['valid_till'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('driver__isnull', True), ('vehicle__isnull', False)), models.Q(('driver__isnull', False), ('vehicle__isnull', True)), _connector='OR'), name='document_belongs_to_exactly_one_holder')],
            },
        ),
    ]
