# Generated by Django 5.2.16 on 2026-08-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="disabled_modules",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("retire", "Retire"),
                    ("login", "Login"),
                    ("impersonate_start", "Impersonate start"),
                    ("impersonate_stop", "Impersonate stop"),
                ],
                max_length=20,
            ),
        ),
    ]
