# Generated by Django 5.2.16 on 2026-08-02 13:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization_disabled_modules_alter_auditlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(blank=True, choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Fleet manager'), ('driver', 'Driver'), ('accountant', 'Accountant')], max_length=20)),
                ('section', models.CharField(max_length=30)),
                ('action', models.CharField(choices=[('view', 'View'), ('add_edit', 'Add / edit'), ('change_status', 'Change status')], max_length=20)),
                ('allowed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('organization', 'role', 'section', 'action'), name='unique_role_permission_override'), models.UniqueConstraint(condition=models.Q(('role', '')), fields=('organization', 'user', 'section', 'action'), name='unique_user_permission_override'), models.CheckConstraint(condition=models.Q(models.Q(('role', ''), ('user__isnull', False)), models.Q(models.Q(('role', ''), _negated=True), ('user__isnull', True)), _connector='OR'), name='permission_subject_is_role_xor_user')],
            },
        ),
    ]
