# Generated by Django 5.2.16 on 2026-08-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economics', '0002_expense_vendor_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
