# Generated by Django 5.2.16 on 2026-08-06 08:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_permission_model'),
        ('economics', '0008_expense_finalize_head'),
        ('vehicles', '0003_vehicleloan_vehicleloaninstallment'),
        ('vendors', '0002_vendorledgerentry_source_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='source_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='source_type',
            field=models.CharField(blank=True, choices=[('trip_expense', 'Trip expense'), ('tyre_service_labour', 'Tyre service — labour'), ('tyre_purchase', 'Tyre service — new tyre purchase'), ('maintenance_labour', 'Maintenance — labour'), ('maintenance_part', 'Maintenance — new part purchase'), ('parts_receipt', 'Parts inventory — receipt')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['organization', 'date'], name='expense_org_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(condition=models.Q(('source_type', ''), _negated=True), fields=('source_type', 'source_id'), name='unique_expense_source'),
        ),
    ]
