# Generated by Django 5.2.16 on 2026-08-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economics', '0010_backfill_expense_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='approval_note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='expense',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
