# Generated by Django 5.2.16 on 2026-08-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economics', '0012_backfill_expense_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='unlisted_vendor_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
