# Generated by Django 5.2.16 on 2026-07-20 10:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('dob', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('emergency_contact', models.CharField(blank=True, max_length=15)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('licence_number', models.CharField(blank=True, max_length=30)),
                ('licence_class', models.CharField(blank=True, choices=[('lmv', 'LMV'), ('hmv', 'HMV'), ('htv', 'HTV / HGV'), ('multiple', 'Multiple')], max_length=12)),
                ('licence_issue_date', models.DateField(blank=True, null=True)),
                ('licence_valid_till', models.DateField(blank=True, null=True)),
                ('issuing_rto', models.CharField(blank=True, max_length=80)),
                ('badge_number', models.CharField(blank=True, max_length=30)),
                ('badge_valid_till', models.DateField(blank=True, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('employment_type', models.CharField(choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('temporary', 'Temporary')], default='permanent', max_length=12)),
                ('wage_basis', models.CharField(choices=[('monthly', 'Monthly salary'), ('per_trip', 'Per trip'), ('per_day', 'Per day')], default='monthly', max_length=12)),
                ('wage_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('has_app_login', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='drivers/')),
                ('licence_copy', models.FileField(blank=True, null=True, upload_to='licences/')),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='ids/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('code__gt', '')), fields=('organization', 'code'), name='uniq_driver_code_per_org')],
            },
        ),
    ]
