# Generated by Django 5.2.16 on 2026-07-27 05:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tyre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(blank=True, max_length=40)),
                ('brand', models.CharField(blank=True, max_length=60)),
                ('size', models.CharField(blank=True, max_length=30)),
                ('serial_number', models.CharField(blank=True, max_length=60)),
                ('fitted_date', models.DateField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('odometer_at_fitting', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('fitted', 'Fitted'), ('spare', 'Spare (in stock)'), ('retired', 'Retired')], default='fitted', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tyres', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['vehicle', 'position'],
            },
        ),
        migrations.CreateModel(
            name='TyreService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_type', models.CharField(choices=[('alignment', 'Wheel alignment'), ('rotation', 'Rotation'), ('balancing', 'Balancing'), ('puncture_repair', 'Puncture repair'), ('replacement', 'Replacement'), ('inspection', 'Inspection')], max_length=20)),
                ('date', models.DateField()),
                ('odometer', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
                ('vendor', models.CharField(blank=True, max_length=120)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organization')),
                ('tyre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='tyres.tyre')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tyre_services', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
