# Generated by Django 5.2.16 on 2026-07-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyreservice',
            name='new_position',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='tyreservice',
            name='tread_depth_in',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
