# Generated by Django 5.2.16 on 2026-07-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyres', '0004_tyreservice_billing_tyreservice_expense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tyreservice',
            name='billing',
            field=models.CharField(blank=True, choices=[('paid', 'Vendor'), ('done_internally', 'Done internally')], default='', max_length=20),
        ),
    ]
