# Generated by Django 5.2.16 on 2026-07-31 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyres', '0005_alter_tyreservice_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyreservice',
            name='previous_tyre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaced_by', to='tyres.tyre'),
        ),
        migrations.AddField(
            model_name='tyreservice',
            name='removal_odometer',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tyreservice',
            name='removal_reason',
            field=models.CharField(blank=True, choices=[('worn_out', 'Worn out'), ('puncture', 'Puncture (unrepairable)'), ('sidewall_damage', 'Sidewall / structural damage'), ('uneven_wear', 'Uneven wear'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='tyreservice',
            name='removal_tread_depth_in',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
