# Generated by Django 5.2.16 on 2026-07-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyres', '0006_tyreservice_previous_tyre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyre',
            name='accumulated_distance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=12),
        ),
    ]
