# Generated by Django 5.2.16 on 2026-07-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyres', '0007_tyre_accumulated_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyreservice',
            name='unlisted_vendor_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
