# Generated by Django 5.2.16 on 2026-08-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyres', '0008_tyreservice_unlisted_vendor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyreservice',
            name='service_person_mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='tyreservice',
            name='service_person_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
