# Generated by Django 5.2.16 on 2026-08-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyres', '0009_tyreservice_service_person_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyreservice',
            name='performed_by',
            field=models.CharField(blank=True, choices=[('internal', 'Our own team'), ('external', 'Outside person / vendor')], max_length=20),
        ),
    ]
