# Generated by Django 5.2.16 on 2026-08-01 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economics', '0003_expense_paid_expense_paid_date_expense_payment_mode'),
        ('tyres', '0010_tyreservice_performed_by'),
        ('vendors', '0002_vendorledgerentry_source_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyreservice',
            name='tyre_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tyre_purchase_services', to='economics.expense'),
        ),
        migrations.AddField(
            model_name='tyreservice',
            name='tyre_source',
            field=models.CharField(blank=True, choices=[('new_purchase', 'Bought new for this job'), ('from_spare', 'Fitted from spare stock')], max_length=20),
        ),
        migrations.AddField(
            model_name='tyreservice',
            name='tyre_unlisted_vendor_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='tyreservice',
            name='tyre_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tyre_purchases', to='vendors.vendor'),
        ),
    ]
