# Generated by Django 5.2.16 on 2026-07-31 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economics', '0002_expense_vendor_fk'),
        ('maintenance', '0002_maintenancelog_vendor_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancelog',
            name='billing',
            field=models.CharField(blank=True, choices=[('paid', 'Paid (external)'), ('done_internally', 'Done internally')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_logs', to='economics.expense'),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='internal_note',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
