# Generated by Django 5.2.16 on 2026-07-31 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_alter_maintenancelog_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancelog',
            name='disposal_plan',
            field=models.CharField(blank=True, choices=[('returned_to_vendor', 'Returned to vendor (core exchange)'), ('scrapped', 'Scrapped / disposed'), ('kept_as_spare', 'Kept as spare / backup'), ('handed_to_owner', 'Handed to vehicle owner'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='old_part_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='old_part_photo',
            field=models.FileField(blank=True, null=True, upload_to='maintenance_parts/'),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='work_type',
            field=models.CharField(blank=True, choices=[('part_replacement', 'Part replacement'), ('consumable', 'Consumable / fluid / labour only')], default='', max_length=20),
        ),
    ]
