# Generated by Django 5.2.16 on 2026-07-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_maintenancelog_disposal_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancelog',
            name='unlisted_vendor_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
