# Generated by Django 5.2.16 on 2026-08-01 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_maintenancelog_unlisted_vendor_name'),
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancelog',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_logs', to='parts.partinventoryitem'),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='inventory_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='parts.partstockmovement'),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='part_quantity',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='part_source',
            field=models.CharField(blank=True, choices=[('new_purchase', 'Bought new for this job'), ('from_inventory', 'Used from spare / inventory')], max_length=20),
        ),
    ]
