# Generated by Django 5.2.16 on 2026-08-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_maintenancelog_inventory_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancelog',
            name='service_person_mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='service_person_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
