# Generated by Django 5.2.16 on 2026-08-01 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economics', '0003_expense_paid_expense_paid_date_expense_payment_mode'),
        ('maintenance', '0009_maintenancelog_performed_by'),
        ('vendors', '0002_vendorledgerentry_source_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancelog',
            name='part_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_part_logs', to='economics.expense'),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='part_unlisted_vendor_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='part_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_part_purchases', to='vendors.vendor'),
        ),
    ]
