# Generated by Django 5.2.16 on 2026-07-20 10:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_number', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('lorry', 'Lorry'), ('four_wheeler', 'Four-wheeler'), ('car', 'Car'), ('two_wheeler', 'Two-wheeler'), ('tractor', 'Tractor'), ('jcb', 'JCB')], max_length=20)),
                ('usage', models.CharField(choices=[('private', 'Private'), ('commercial', 'Commercial')], default='commercial', max_length=12)),
                ('metering_unit', models.CharField(blank=True, choices=[('km', 'Kilometres'), ('hours', 'Hours')], max_length=6)),
                ('tracking_mode', models.CharField(choices=[('gps', 'GPS'), ('manual', 'Manual')], default='manual', max_length=6)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('rto', models.CharField(blank=True, max_length=80)),
                ('chassis_number', models.CharField(blank=True, max_length=40)),
                ('engine_number', models.CharField(blank=True, max_length=40)),
                ('rc_valid_till', models.DateField(blank=True, null=True)),
                ('fuel_norm', models.CharField(blank=True, max_length=20)),
                ('rto_vehicle_class', models.CharField(blank=True, max_length=40)),
                ('maker', models.CharField(blank=True, max_length=80)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('mfg_year', models.PositiveIntegerField(blank=True, null=True)),
                ('fuel_type', models.CharField(blank=True, choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('cng', 'CNG'), ('lpg', 'LPG'), ('electric', 'Electric')], max_length=12)),
                ('cc', models.PositiveIntegerField(blank=True, null=True)),
                ('seating_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('gvw', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('colour', models.CharField(blank=True, max_length=40)),
                ('body_type', models.CharField(blank=True, max_length=40)),
                ('owner_name', models.CharField(blank=True, max_length=120)),
                ('owner_relation', models.CharField(blank=True, max_length=40)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('financier', models.CharField(blank=True, max_length=120)),
                ('hypothecation_till', models.DateField(blank=True, null=True)),
                ('number_of_owners', models.PositiveIntegerField(default=1)),
                ('acquisition_type', models.CharField(choices=[('new', 'New'), ('second_hand', 'Second-hand')], default='new', max_length=12)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('previous_owner', models.CharField(blank=True, max_length=120)),
                ('ownership_transfer_date', models.DateField(blank=True, null=True)),
                ('number_of_tyres', models.PositiveIntegerField(default=6)),
                ('spare_tyres', models.PositiveIntegerField(default=1)),
                ('axle_layout', models.CharField(blank=True, choices=[('lorry_6', 'Lorry · 6-wheeler'), ('lorry_10', 'Lorry · 10-wheeler'), ('lorry_12', 'Lorry · 12-wheeler'), ('lorry_14', 'Lorry · 14-wheeler'), ('lorry_16', 'Lorry · 16-wheeler'), ('car_4_1', 'Car · 4 + 1'), ('two_wheeler_2', 'Two-wheeler · 2'), ('tractor', 'Tractor · small front + big rear')], max_length=20)),
                ('fleet_id', models.CharField(blank=True, max_length=40)),
                ('current_meter', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
                ('meter_reading_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rc_copy', models.FileField(blank=True, null=True, upload_to='rc/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['registration_number'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'registration_number'), name='uniq_registration_per_org')],
            },
        ),
    ]
