# Generated by Django 5.2.16 on 2026-08-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='category',
            field=models.CharField(choices=[('lorry', 'Lorry'), ('tipper', 'Tipper'), ('four_wheeler', 'Four-wheeler'), ('car', 'Car'), ('two_wheeler', 'Two-wheeler'), ('tractor', 'Tractor'), ('jcb', 'JCB'), ('rig', 'Rig')], max_length=20),
        ),
    ]
