# Generated by Django 5.2.16 on 2026-08-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicleloan_vehicleloaninstallment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='broker_commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='broker_info',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='broker_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='previous_rc_copy',
            field=models.FileField(blank=True, null=True, upload_to='rc/'),
        ),
        migrations.AddField(
            model_name='vehicleloan',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='axle_layout',
            field=models.CharField(blank=True, choices=[('lorry_6', 'Lorry · 6-wheeler'), ('lorry_10', 'Lorry · 10-wheeler'), ('lorry_12', 'Lorry · 12-wheeler'), ('lorry_14', 'Lorry · 14-wheeler'), ('lorry_16', 'Lorry · 16-wheeler'), ('car_4_1', 'Car · 4 + 1'), ('two_wheeler_2', 'Two-wheeler · 2'), ('tractor', 'Tractor · small front + big rear'), ('tipper_6', 'Tipper · 6-wheeler'), ('tipper_10', 'Tipper · 10-wheeler'), ('tipper_12', 'Tipper · 12-wheeler'), ('jcb_4', 'JCB · 4-wheel'), ('rig_6', 'Rig · 6-wheeler'), ('rig_10', 'Rig · 10-wheeler'), ('four_wheeler_4_1', 'Four-wheeler · 4 + 1')], max_length=20),
        ),
    ]
