# Generated by Django 5.2.16 on 2026-08-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehicle_broker_commission_vehicle_broker_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='rc_copy_back',
            field=models.FileField(blank=True, null=True, upload_to='rc/'),
        ),
    ]
