# Generated by Django 5.2.16 on 2026-07-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorledgerentry',
            name='source_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='vendorledgerentry',
            name='source_model',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
