# Generated by Django 5.2.16 on 2026-07-29 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('advance', 'Advance'), ('wage', 'Wage'), ('bonus', 'Bonus'), ('deduction', 'Deduction'), ('payment', 'Payment')], max_length=12),
        ),
    ]
