# Generated by Django 5.2.16 on 2026-07-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_alter_driverledgerentry_entry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverledgerentry',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank', 'Bank transfer'), ('upi', 'UPI')], max_length=10),
        ),
        migrations.AddField(
            model_name='driverledgerentry',
            name='subtype',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
