# Generated by Django 5.2.16 on 2026-08-01 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_fuellog_fuel_station_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripsheet',
            name='wage_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operations.driverledgerentry'),
        ),
    ]
