# Generated by Django 5.2.16 on 2026-08-01 16:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('operations', '0005_tripsheet_wage_entry'),
        ('vendors', '0002_vendorledgerentry_source_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tripsheet',
            name='advance_return_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operations.driverledgerentry'),
        ),
        migrations.AddField(
            model_name='tripsheet',
            name='reconciliation_override_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='tripsheet',
            name='reimbursed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tripsheet',
            name='reimbursed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripsheet',
            name='reimbursement_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operations.driverledgerentry'),
        ),
        migrations.AddField(
            model_name='tripsheet',
            name='returned_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tripsheet',
            name='returned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripsheet',
            name='returned_received_by',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='tripsheet',
            name='trip_no',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='driverledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('advance', 'Advance'), ('wage', 'Wage'), ('bonus', 'Bonus'), ('deduction', 'Deduction'), ('payment', 'Payment'), ('advance_return', 'Advance returned'), ('reimbursement', 'Expense reimbursement')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tripsheet',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=10),
        ),
        migrations.CreateModel(
            name='TripAdvance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('given_by', models.CharField(blank=True, max_length=120)),
                ('date', models.DateField()),
                ('payment_mode', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank', 'Bank transfer'), ('upi', 'UPI')], max_length=10)),
                ('remarks', models.CharField(blank=True, max_length=300)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operations.driverledgerentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organization')),
                ('trip_sheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advances', to='operations.tripsheet')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('fuel', 'Fuel'), ('toll_fastag', 'Toll / FASTag'), ('loading', 'Loading'), ('unloading', 'Unloading'), ('parking', 'Parking'), ('police_rto', 'Police / RTO'), ('weighbridge', 'Weighbridge'), ('casing_material', 'Casing / material'), ('repairs_on_road', 'Repairs on road'), ('food', 'Food'), ('tea_refreshments', 'Tea / refreshments'), ('bata', 'Bata'), ('misc', 'Misc')], max_length=20)),
                ('paid_from', models.CharField(choices=[('advance', 'From advance'), ('company_direct', 'Company paid directly'), ('driver_own', "Driver's own money")], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('date', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organization')),
                ('trip_sheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_expenses', to='operations.tripsheet')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trip_expenses', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
