# Generated by Django 5.2.16 on 2026-08-01 16:19
"""TripSheetStatus.OPEN was renamed to DRAFT (the workflow gained
SUBMITTED/APPROVED between draft and closed) - existing rows carrying the
old string need to move over, or they'd stop matching any known status."""
from django.db import migrations


def open_to_draft(apps, schema_editor):
    TripSheet = apps.get_model("operations", "TripSheet")
    TripSheet.objects.filter(status="open").update(status="draft")


def draft_to_open(apps, schema_editor):
    TripSheet = apps.get_model("operations", "TripSheet")
    TripSheet.objects.filter(status="draft").update(status="open")


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_tripsheet_advance_return_entry_and_more'),
    ]

    operations = [
        migrations.RunPython(open_to_draft, draft_to_open),
    ]
