# Generated by Django 5.2.16 on 2026-08-02 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('operations', '0007_rename_open_status_to_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripleg',
            name='basis',
            field=models.CharField(blank=True, choices=[('per_km', 'Per km'), ('per_ton', 'Per ton'), ('per_trip', 'Per trip'), ('per_load', 'Per load'), ('fixed', 'Fixed')], max_length=10),
        ),
        migrations.AddField(
            model_name='tripleg',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trip_legs', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='tripleg',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tripleg',
            name='load_status',
            field=models.CharField(blank=True, choices=[('loaded', 'Loaded'), ('empty', 'Empty (deadhead)')], max_length=10),
        ),
        migrations.AddField(
            model_name='tripleg',
            name='material',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='tripleg',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tripleg',
            name='tonnage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
