# Generated by Django 5.2.16 on 2026-08-02 05:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('customers', '0001_initial'),
        ('operations', '0008_tripleg_basis_tripleg_customer_tripleg_distance_km_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tripsheet',
            name='working_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('site', models.CharField(blank=True, max_length=120)),
                ('work_type', models.CharField(blank=True, max_length=120)),
                ('basis', models.CharField(blank=True, choices=[('per_hour', 'Per hour'), ('per_acre', 'Per acre'), ('per_trip', 'Per trip'), ('per_feet', 'Per feet'), ('per_bore', 'Per bore'), ('fixed', 'Fixed')], max_length=10)),
                ('qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('overtime_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('overtime_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_billable', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remarks', models.CharField(blank=True, max_length=300)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_items', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organization')),
                ('trip_sheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_items', to='operations.tripsheet')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['trip_sheet', 'sequence'],
            },
        ),
    ]
