# Generated by Django 5.2.16 on 2026-08-02 07:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('customers', '0001_initial'),
        ('operations', '0009_tripsheet_working_hours_workitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_place', models.CharField(max_length=120)),
                ('to_place', models.CharField(max_length=120)),
                ('material', models.CharField(blank=True, max_length=120)),
                ('basis', models.CharField(choices=[('per_km', 'Per km'), ('per_ton', 'Per ton'), ('per_trip', 'Per trip'), ('per_load', 'Per load'), ('fixed', 'Fixed')], max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('load_pattern', models.CharField(blank=True, max_length=40)),
                ('effective_date', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='route_rates', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.CharField(blank=True, max_length=80)),
                ('work_type', models.CharField(max_length=120)),
                ('basis', models.CharField(choices=[('per_hour', 'Per hour'), ('per_acre', 'Per acre'), ('per_trip', 'Per trip'), ('per_feet', 'Per feet'), ('per_bore', 'Per bore'), ('fixed', 'Fixed')], max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_billable', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('overtime_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('effective_date', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_rates', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_date'],
            },
        ),
    ]
