# Generated by Django 5.2.16 on 2026-08-02 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economics', '0003_expense_paid_expense_paid_date_expense_payment_mode'),
        ('operations', '0010_routerate_workrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripexpense',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='economics.expense'),
        ),
        migrations.AddField(
            model_name='tripexpense',
            name='fuel_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operations.fuellog'),
        ),
        migrations.AddField(
            model_name='tripexpense',
            name='litres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='tripexpense',
            name='rate_per_litre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
