# Generated by Django 5.2.16 on 2026-08-02 23:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_permission_model'),
        ('drivers', '0002_driver_advance_limit'),
        ('operations', '0012_tripexpense_expense_head'),
        ('vehicles', '0002_alter_vehicle_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tripsheet',
            constraint=models.UniqueConstraint(condition=models.Q(('trip_no', ''), _negated=True), fields=('organization', 'trip_no'), name='unique_trip_no_per_org'),
        ),
    ]
