# Generated by Django 5.2.16 on 2026-08-06 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_advance_limit'),
        ('operations', '0013_tripsheet_unique_trip_no_per_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuellog',
            name='approval_note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='fuellog',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fuel_logs', to='drivers.driver'),
        ),
        migrations.AlterField(
            model_name='fuellog',
            name='status',
            field=models.CharField(choices=[('draft', 'Open'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=10),
        ),
    ]
