# Generated by Django 5.2.16 on 2026-08-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0015_backfill_fuellog_driver_and_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuellog',
            name='filled_by',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
